site_name: Getting Started
nav:
    - Knowledge Prep: index.md
    - Environment Setup: env-setup.md
    - Basic Code Structure: code-struct.md
    - roboRIO Setup: rio-setup.md
    - Your First Robot: robot1.md
theme: readthedocs